language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nose sphinx pyyaml matplotlib cython numpy scipy astropy pillow
  - conda activate test-environment
  - conda install -c conda-forge cfitsio=3.430 libcblas gsl -n test-environment
  - conda install -c conda-forge namaster -n test-environment
  - pip install healpy
  - git clone https://github.com/simonsobs/pixell.git
  - cd pixell
  - python setup.py install --user
  - cd ../
  - pip install codecov
  - pip install --user travis-sphinx
  - export PATH=$HOME/.local/bin:$PATH
  - python setup.py install
addons:
  apt:
    packages:
      - gfortran

# Your test script goes here
script:
  - nosetests --with-coverage
  - travis-sphinx build

# Push the results back to codecov
after_success:
  - codecov
  - travis-sphinx deploy
